name: check
on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4.7.1
        with:
          java-version: '16'
          distribution: 'adopt'
      - run: ./gradlew check
