on:
  push:
    branches:
      - master

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4.7.1
        with:
          java-version: '22'
          distribution: 'adopt'
      - run: ./gradlew dokkaHtml
      - uses: actions/configure-pages@v5.0.0
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: indexer/build/dokka/html
      - uses: actions/deploy-pages@v4
